---
title: "R Notebook"
output: pdf_document
---
### Import Libraries

```{r}
library(tidyverse)
library(ggplot2)
library(psych)
library(dplyr)
```

### Load our Data

```{r}
data <- read.csv("assets/StudentsPerformance.csv")
data%>%head()
ndata<-mutate(data,mean=(`math.score`+`reading.score`+`writing.score`)/3) #mean of three score
table(data$parental.level.of.education)
table(data$lunch)
```

### Comparing the Reading and Writing Scores again Math Scores

```{r}
girl_data<-data%>%filter(gender=='female')
boy_data<-data%>%filter(gender=='male')
ggplot()+
  geom_point(girl_data,mapping=aes(`math.score`,`reading.score`,color='female'))+
  geom_point(boy_data,mapping=aes(`math.score`,`reading.score`,color='male'))+labs(title='Math and Reading score')
ggplot()+
  geom_point(girl_data,mapping=aes(`math.score`,`writing.score`,color='female'))+
  geom_point(boy_data,mapping = aes(`math.score`,`writing.score`,color='male'))+labs(title='Math and Writing score')
```
Now we comparing Reading and Writing Scores

```{r}
ggplot()+
  geom_point(girl_data,mapping=aes(`reading.score`,`writing.score`,color='female'),alpha=1/2)+
  geom_point(boy_data,mapping = aes(`reading.score`,`writing.score`,color='male'),alpha=1/2)+labs(title='Reading and Writing')
```

```{r}
pairs.panels(data[6:8])
```

The plot above shows that females have a higher reading/wriitng score and males tend to have higher math scores

### Averages Scores of Each Group

```{r}
ndata%>%
group_by(race.ethnicity)%>%
summarize(avg_score=round(sum(mean)/n(),1))%>%
ggplot(aes(race.ethnicity,avg_score,fill=race.ethnicity))+geom_bar(stat='identity')+
geom_text(aes(label = avg_score))+coord_flip()+labs(title='Average score of each group')+guides(fill=F)

```

